[instances.numbers]
Arm = 1
Gripper = 2
Printer = 3

[Base]
heartbeat = 0
status = "offline"
error = ""
message = ""
progId = 0
start = false

[Printer.Control]
PartRemoved = false
BedCleaned = false
File = "Unknown"
JogX = 0.0
JogY = 0.0
JogZ = 0.0
JogSpeed = 0.0
Feedrate = 0.0
Extrude = 0.0

[Printer.Data]
Read = false
End = false
APIResp = "unknown"
tNozTarget = 0.0
tNozTOffset = 0.0
tBedTarget = 0.0
tBedOffset = 0.0
JobTimeEst = 0.0
FilaLenEst = 0.0
JobFile = "Unknown"
JobProgress = 0.0
JobTime = 0.0
JobTimeLeft = 0.0

[Gripper.Control]
GripperControl = false
GripperAct = false
GripperSpeed = 0.0
GripperForce = 0.0
GripperPos = 0.0

[Gripper.Data]
GripperAct = false
GripperSpeed = 0.0
GripperForce = 0.0
GripperPos = 0.0

[Arm.Control]
Joi1 = 0.0
Joi2 = 0.0
Joi3 = 0.0
Joi4 = 0.0
Joi5 = 0.0
Joi6 = 0.0
Joi7 = 0.0
Vel = 0.0
PosX = 0.0
PosY = 0.0
PosZ = 0.0
RotA = 0.0
RotB = 0.0
RotC = 0.0

[Arm.Data]
Joi1 = 0.0
Joi2 = 0.0
Joi3 = 0.0
Joi4 = 0.0
Joi5 = 0.0
Joi6 = 0.0
Joi7 = 0.0
Tor1 = 0.0
Tor2 = 0.0
Tor3 = 0.0
Tor4 = 0.0
Tor5 = 0.0
Tor6 = 0.0
Tor7 = 0.0
PosX = 0.0
PosY = 0.0
PosZ = 0.0
RotA = 0.0
RotB = 0.0
RotC = 0.0
ForX = 0.0
ForY = 0.0
ForZ = 0.0
MomA = 0.0
MomB = 0.0
MomC = 0.0
Disconnect = false
Connected = true
End = false
Ready = false
