[tool.poetry]
name = "opcua-server"
version = "0.1.0"
description = ""
authors = ["Jicheng Zhi <jzhi0004@student.monash.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
